### ISSUE TITLE
sign-off on v0.1.0

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdakits-whitepaper#8]
All authors should sign-off on the 0.1.0 version with any of the changes since v0.1.0b.

Please check the box.

- [x] @IAlibay 
- [x] @jbarnoud 
- [x] @orbeckst 
- [x] @richardjgowers 
- [x] @fiona-naughton 
- [x] @lilyminium 

Once everybody is ok with the white paper, we can release it #2 .

**Comment by orbeckst** [comment]
@jbarnoud , the propkatraj example was updated #12

**Comment by orbeckst** [comment]
@richardjgowers please have a look and add your ORCID if you want it to appear. 

If there's anything that needs changing please do so or let us know as soon as possible, otherwise please formally tick the box above. 

We really should have the white paper out before the ACS meeting next week. Given that we will likely also need a few days for the blog post https://github.com/MDAnalysis/MDAnalysis.github.io/issues/241 , it would be really good to have your final comments. Thanks.

**Comment by richardjgowers** [comment]
I added my orcid info in a PR, paper is looking good

**Comment by orbeckst** [comment]
Awesome, thank you everyone. Will make a 0.1.0 version.
